### ISSUE TITLE
buildCache fails (resource exhausted)

### ISSUE THREAD

**Issue by schell** [Twinside/FontyFruity#14]
buildCache is failing about half the time I call it at the beginning of my app. Here is the exception:

    /Library/Fonts/Telugu Sangam MN.ttc: openBinaryFile: resource exhausted (Too many open files)

The exact font it errs on is different (almost) every time. I'm running on Mac OS X 10.11.2 and ghc 7.10.2.

**Comment by Twinside** [comment]
I get an idea why it may happen, the key type of the map is not fully strict, and so it may keep a thunk to the file in some cases. I'll make it more strict, hopping you can retest it with it

**Comment by schell** [comment]
I'll test it out ASAP.

**Comment by schell** [comment]
@Twinside - unfortunately the problem persists :(.

**Comment by schell** [comment]
@Twinside - turns out I was calling `buildCache` twice... ...once on the main thread and once in a secondary thread. *facepalm*

Now that I'm only running `buildCache` once every works fine, I'm not seeing the problem any longer. Actually building the cache is really fast now too!

**Comment by Twinside** [comment]
I'm keeping the strictness though, it won't hurt in that cas

**Comment by ianmbloom** [comment]
Hi, 
We just had this issue pop up on a mac system, when we tried use buildCache as part of https://github.com/ianmbloom/gudni. It's inconsistent so for example it won't happen right after the full reboot.
I was looking at whether there was a simple way to switch FontyFruity away from using Data.ByteStream.Lazy in this context, because the readFile function is known to hold files open.
